### ISSUE TITLE
Websocket header file typo

### ISSUE THREAD

**Issue by c-lgrant** [lganzzzo/oatpp-example-websocket#1]
In the following file:
oatpp-example-websocket/main/src/websocket/MySocketListener.hpp
      
The include 
```
#include "oatpp-websocket/Websocket.hpp"
```
should be 
```
#include "oatpp-websocket/WebSocket.hpp"
```

Notice the capitalisation in WebSocket.hpp

**Comment by lganzzzo** [comment]
Fixed in https://github.com/lganzzzo/oatpp-example-websocket/commit/b722b8327751b439b03eaad8681e9b44fb37607a

Thanks a lot!
