### ISSUE TITLE
Possible to send message to specific WebSocket Connection ID

### ISSUE THREAD

**Issue by rebootcode** [lganzzzo/oatpp-example-websocket#2]
I can't see any example where a message can be emitted to a specific websocket connection id.

Is it possible for this framework?

**Comment by lganzzzo** [comment]
Hello @rebootcode ,

Depends on what you mean by "Client Id".

It's possible, and may implemented in many different ways.

Example:
- Client sends "Client Id" when connected to server.
- Server builds map <clientId, WebSocket>
- Server then may send messages to a specific Client - as it knows which "clientId" correspond to which WebSocket.

Regards,
Leonid

**Comment by rebootcode** [comment]
Sorry from client ID, I mean WebSocket connection ID. I can not find any documentation to send message to a specific WebSocket connection ID

Like is every connection in WebSocket identifiable with a unique ID?

For example, let's say.

The first peer connected to WebSocket and the framework creates unique connection ID and store his session, now when he sends any WebSocket event request, we can get his connection ID and know who sent what?

**Comment by lganzzzo** [comment]
@rebootcode ,

In WebSocket you definitely know who sent what.
In case of oatpp `WebSocket` instance represents one connection to a peer.

Please take a look at this line https://github.com/lganzzzo/oatpp-example-websocket/blob/master/src/websocket/MySocketListener.hpp#L64

Here - WebSocket listener is created for each new  WebSocket instance.
So in this particular case of this example each WebSocket listener will get events for a one peer associated with it.

---

Also here https://github.com/lganzzzo/oatpp-example-websocket/blob/master/src/websocket/MySocketListener.hpp#L39 you can see that websocket instance is passed with each websocket event to the listener. So listener can always identify a peer who sent him a message.

Regards,
Leonid

**Comment by rebootcode** [comment]
ok, I just found here - https://github.com/oatpp/oatpp-websocket/blob/master/src/oatpp-websocket/WebSocket.hpp#L54

the socket is the WebSocket connection ID.

Sorry for the confusion, coming from Golang WebSocket and got juggled up. 

Thanks for sharing the info, I needed this to create "room/channel" like an option to broadcast message to a specific group of users.

For newcomers like me, More examples or More detail overview of how whole architecture runs would be extremely helpful.

Any IDE support for this framework?

**Comment by lganzzzo** [comment]
@rebootcode ,

> Thanks for sharing the info, I needed this to create "room/channel" like an option to broadcast message to a specific group of users.

Cool, please let me know if have more questions, or if you face any problems.

> For newcomers like me, More examples or More detail overview of how whole architecture runs would be extremely helpful.

I have recently created a step-by-step guide, you may take a look - https://oatpp.io/docs/start/step-by-step/ .

> Any IDE support for this framework?

Personally I am using CLion. Can't say it's perfect though

---

See also:

- [Collection of examples](https://oatpp.io/examples/crud/)
- [New repo with websocket examples](https://github.com/oatpp/example-websocket)

Best Regards,
Leonid
